name: plain_registry_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  equatable: ^2.0.7
  sqflite: ^2.4.1
  intl: ^0.20.1
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  camera: ^0.11.0+2
  wakelock_plus: ^1.2.10
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  mime: ^2.0.0
  video_player: ^2.9.2
  flutter_markdown: ^0.7.5
  path: ^1.9.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - mocks/
    # - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
